name: Dependency Review

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Check dependency changes
        uses: actions/dependency-review-action@v5
        with:
          allow-ghsas: GHSA-537c-gmf6-5ccf
          show-patched-versions: true
